const ProjectData1 = [
  {
    "id":"1",
    "pic":"/picture1.jpg",
  "man_in_charge": "John Doe",
  "header": "Banner Design Update",
  "content": "Update the customer page layout for the website.",
  "deadline": "March 05, 2022",
  "status": "In Progress",
  "category": "Design",
  "assignee": "Alice Smith",
  "milestone": "Website Redesign",
  "issue_type": "Task"
},
{
    "id":"2",
    "pic":'',
  "man_in_charge": "Jane Smith",
  "header": "SEO Optimization",
  "content": "Optimize the website's SEO for better search rankings.",
  "deadline": "April 10, 2022",
  "status": "Not Started",
  "category": "Marketing",
  "assignee": "Robert Johnson",
  "milestone": "Digital Marketing Campaign",
  "issue_type": "Task"
},
{
    "id":"3",
    "pic":'',
  "man_in_charge": "Michael Brown",
  "header": "Bug Fixing",
  "content": "Fix critical bugs reported by users.",
  "deadline": "February 20, 2022",
  "status": "Completed",
  "category": "Development",
  "assignee": "David Wilson",
  "milestone": "Bug Fixes",
  "issue_type": "Bug"
},
{
    "id":"4",
    "pic":'',
  "man_in_charge": "Emily Davis",
  "header": "Content Writing",
  "content": "Create engaging content for the blog posts.",
  "deadline": "March 15, 2022",
  "status": "In Progress",
  "category": "Content",
  "assignee": "Olivia Anderson",
  "milestone": "Content Strategy",
  "issue_type": "Task"
},
{
    "id":"5",
    "pic":'',
  "man_in_charge": "William Lee",
  "header": "Security Audit",
  "content": "Conduct a security audit of the website.",
  "deadline": "April 30, 2022",
  "status": "Not Started",
  "category": "Security",
  "assignee": "Sophia White",
  "milestone": "Security Enhancement",
  "issue_type": "Task"
},
{"id":"6",
"pic":'',
  "man_in_charge": "Daniel Harris",
  "header": "Mobile App Development",
  "content": "Develop a mobile app for the company.",
  "deadline": "May 20, 2022",
  "status": "In Progress",
  "category": "Development",
  "assignee": "Ava Martinez",
  "milestone": "Mobile App Launch",
  "issue_type": "Feature"
},
{
    "id":"7",
    "pic":'',
  "man_in_charge": "Sophia Johnson",
  "header": "Customer Support Training",
  "content": "Provide training to the customer support team.",
  "deadline": "March 31, 2022",
  "status": "Not Started",
  "category": "Training",
  "assignee": "Lucas Brown",
  "milestone": "Training Program",
  "issue_type": "Task"
},
{
    "id":"8",
    "pic":'',
  "man_in_charge": "Ethan Martinez",
  "header": "Graphic Design for Campaign",
  "content": "Design graphics for the upcoming marketing campaign.",
  "deadline": "April 15, 2022",
  "status": "Not Started",
  "category": "Design",
  "assignee": "Chloe Adams",
  "milestone": "Marketing Campaign",
  "issue_type": "Task"
},
{
    "id":"9",
    "pic":'',
  "man_in_charge": "Olivia Anderson",
  "header": "Database Migration",
  "content": "Migrate the database to a new server for improved performance.",
  "deadline": "March 25, 2022",
  "status": "In Progress",
  "category": "Database ",
  "assignee": "Mia Davis",
  "milestone": "Database Upgrade",
  "issue_type": "Task"
},
{
    "id":"10",
    "pic":'',
  "man_in_charge": "David Wilson",
  "header": "User Interface Enhancement",
  "content": "Enhance the user interface for better user experience.",
  "deadline": "May 10, 2022",
  "status": "Not Started",
  "category": "Development ",
  "assignee": "Ella Smith",
  "milestone": "UI/UX Improvements ",
  "issue_type": "Enhancement"
}]
  
  export default ProjectData1;
  