const ProjectData2 = [
    {'id': '1', 
    'pic': '/project2-picture1.jpg',
     'man_in_charge': 'Thomas Clark - Project 2', 
     'header': 'Task 1 Header - Project 2', 
     'content': 'Description of task 1 - Project 2 Task 1.', 
     'deadline': '2023-002-002', 
     'status': 'Not Started', 
     'category': 'Category', 
     'assignee': 'Nancy Carter - Project 2', 
     'milestone': 'Milestone 1 - Project 2', 
     'issue_type': 'Type'
    }, 
      {
        'id': '2', 
        'pic': '/project2-picture2.jpg', 
        'man_in_charge': 'Lisa Ray - Project 2', 
        'header': 'Task 2 Header - Project 2', 
        'content': 'Description of task 2 - Project 2 Task 2.', 
        'deadline': '2023-003-003', 
        'status': 'Completed', 
        'category': 'Category', 
        'assignee': 'Gary Stewart - Project 2', 
        'milestone': 'Milestone 2 - Project 2', 
        'issue_type': 'Type'
    }, 
    {
        'id': '3', 
        'pic': '/project2-picture3.jpg',
        'man_in_charge': 'Patricia Lewis - Project 2', 
        'header': 'Task 3 Header - Project 2', 
        'content': 'Description of task 3 - Project 2 Task 3.', 
        'deadline': '2023-004-004', 
        'status': 'In Progress', 
        'category': 'Category', 'assignee': 
        'Rachel Evans - Project 2', 
        'milestone': 'Milestone 3 - Project 2', 
        'issue_type': 'Type'
    }, 
    {
        'id': '4', 
        'pic': '/project2-picture4.jpg', 
        'man_in_charge': 'Brian Adams - Project 2', 
        'header': 'Task 4 Header - Project 2', 
        'content': 'Description of task 4 - Project 2 Task 4.', 
        'deadline': '2023-005-005', 
        'status': 'Not Started',
        'category': 'Category', 
        'assignee': 'Anna Walker - Project 2', 
        'milestone': 'Milestone 4 - Project 2', 
        'issue_type': 'Other'
    }, 
    {
        'id': '5', 'pic': '/project2-picture5.jpg',
        'man_in_charge': 'Susan Clark - Project 2', 
        'header': 'Task 5 Header - Project 2', 
        'content': 'Description of task 5 - Project 2 Task 5.', 
        'deadline': '2023-006-006', 
        'status': 'Completed', 
        'category': 'Other', 
        'assignee': 'Frank Wright - Project 2', 
        'milestone': 'Milestone 5 - Project 2', 
        'issue_type': 'Type'
    }, 
    {
        'id': '6', 
        'pic': '/project2-picture6.jpg', 
        'man_in_charge': 'Kevin Turner - Project 2', 
        'header': 'Task 6 Header - Project 2', 
        'content': 'Description of task 6 - Project 2 Task 6.', 
        'deadline': '2023-007-007', 
        'status': 'In Progress', 
        'category': 'Category', 
        'assignee': 'Judy Harris - Project 2', 
        'milestone': 'Milestone 6 - Project 2', 
        'issue_type': 'Type'
    }, 
    {
        'id': '7', 
        'pic': '/project2-picture7.jpg', 
        'man_in_charge': 'Sarah Moore - Project 2', 
        'header': 'Task 7 Header - Project 2', 
        'content': 'Description of task 7 - Project 2 Task 7.', 
        'deadline': '2023-008-008', 
        'status': 'Not Started', 
        'category': 'Category', 
        'assignee': 'Carl Benz - Project 2', 
        'milestone': 'Milestone 7 - Project 2', 
        'issue_type': 'Type'
    }, 
    {'id': '8', 'pic': '/project2-picture8.jpg', 
    'man_in_charge': 'James Corden - Project 2', 
    'header': 'Task 8 Header - Project 2', 
    'content': 'Description of task 8 - Project 2 Task 8.', 
    'deadline': '2023-009-009', 
    'status': 'Completed', 
    'category': 'Category', 
    'assignee': 'Monica Bellucci - Project 2', 
    'milestone': 'Milestone 8 - Project 2', 
    'issue_type': 'Other'
}, 
{
    'id': '9', 
    'pic': '/project2-picture9.jpg', 
    'man_in_charge': 'Lucy Hale - Project 2', 
    'header': 'Task 9 Header - Project 2', 
    'content': 'Description of task 9 - Project 2 Task 9.', 
    'deadline': '2023-010-010', 
    'status': 'In Progress', 
    'category': 'Category', 
    'assignee': 'Ethan Hunt - Project 2', 
    'milestone': 'Milestone 9 - Project 2', 
    'issue_type': 'Type'
}, 
{
    'id': '10', 
    'pic': '/project2-picture10.jpg', 
    'man_in_charge': 'Mark Sloan - Project 2', 
    'header': 'Task 10 Header - Project 2', 
    'content': 'Description of task 10 - Project 2 Task 10.', 
    'deadline': '2023-011-011', 
    'status': 'Not Started', 
    'category': 'Other', 
    'assignee': 'Diana Barry - Project 2', 
    'milestone': 'Milestone 10 - Project 2', 
    'issue_type': 'Type'
}, 
{
    'id': '11', 
    'pic': '/project2-picture11.jpg', 
    'man_in_charge': 'Nina Morris - Project 2', 
    'header': 'Task 11 Header - Project 2', 
    'content': 'Description of task 11 - Project 2 Task 11.', 
    'deadline': '2023-012-012', 
    'status': 'Completed', 
    'category': 'Category', 
    'assignee': 'Peter Parker - Project 2', 
    'milestone': 'Milestone 11 - Project 2', 
    'issue_type': 'Type'
}, {
    'id': '12', 
    'pic': '/project2-picture12.jpg', 
    'man_in_charge': 'Tony Stark - Project 2', 
    'header': 'Task 12 Header - Project 2', 
    'content': 'Description of task 12 - Project 2 Task 12.', 
    'deadline': '2023-001-013', 
    'status': 'In Progress', 
    'category': 'Category', 
    'assignee': 'Lois Lane - Project 2', 
    'milestone': 'Milestone 12 - Project 2', 
    'issue_type': 'Other'
}, 
{
    'id': '13', 
    'pic': '/project2-picture13.jpg', 
    'man_in_charge': 'Oliver Queen - Project 2', 
    'header': 'Task 13 Header - Project 2', 
    'content': 'Description of task 13 - Project 2 Task 13.', 
    'deadline': '2023-002-014', 
    'status': 'Not Started', 
    'category': 'Category', 
    'assignee': 'Steve Rogers - Project 2', 
    'milestone': 'Milestone 13 - Project 2',
    'issue_type': 'Type'
}, 
{
    'id': '14', 
    'pic': '/project2-picture14.jpg', 
    'man_in_charge': 'Bruce Wayne - Project 2',
    'header': 'Task 14 Header - Project 2', 
    'content': 'Description of task 14 - Project 2 Task 14.', 
    'deadline': '2023-003-015', 
    'status': 'Completed', 
    'category': 'Category', 
    'assignee': 'Natasha Romanoff - Project 2', 
    'milestone': 'Milestone 14 - Project 2', 
    'issue_type': 'Type'
}, 
{
    'id': '15', 'pic': '/project2-picture15.jpg', 
    'man_in_charge': 'Clark Kent - Project 2', 
    'header': 'Task 15 Header - Project 2', 
    'content': 'Description of task 15 - Project 2 Task 15.', 
    'deadline': '2023-004-016', 
    'status': 'In Progress', 
    'category': 'Other', 
    'assignee': 'Wanda Maximoff - Project 2', 
    'milestone': 'Milestone 15 - Project 2', 
    'issue_type': 'Type'
}, 
{
    'id': '16', 
    'pic': '/project2-picture16.jpg', 
    'man_in_charge': 'Diana Prince - Project 2', 
    'header': 'Task 16 Header - Project 2', 
    'content': 'Description of task 16 - Project 2 Task 16.', 
    'deadline': '2023-005-017', 
    'status': 'Not Started', 
    'category': 'Category', 
    'assignee': 'Tony Halme - Project 2', 
    'milestone': 'Milestone 16 - Project 2', 
    'issue_type': 'Other'
}, 
{
    'id': '17', 
    'pic': '/project2-picture17.jpg', 
    'man_in_charge': 'Barry Allen - Project 2', 
    'header': 'Task 17 Header - Project 2', 
    'content': 'Description of task 17 - Project 2 Task 17.', 
    'deadline': '2023-006-018', 
    'status': 'Completed', 
    'category': 'Category', 
    'assignee': 'Peggy Carter - Project 2', 
    'milestone': 'Milestone 17 - Project 2', 
    'issue_type': 'Type'
}, 
{
    'id': '18', 
    'pic': '/project2-picture18.jpg', 
    'man_in_charge': 'Hal Jordan - Project 2', 
    'header': 'Task 18 Header - Project 2', 
    'content': 'Description of task 18 - Project 2 Task 18.', 
    'deadline': '2023-007-019', 
    'status': 'In Progress', 
    'category': 'Category', 
    'assignee': 'Bruce Banner - Project 2', 
    'milestone': 'Milestone 18 - Project 2', 
    'issue_type': 'Type'
}, 
{
    'id': '19', 
    'pic': '/project2-picture19.jpg', 
    'man_in_charge': 'Arthur Curry - Project 2', 
    'header': 'Task 19 Header - Project 2', 
    'content': 'Description of task 19 - Project 2 Task 19.', 
    'deadline': '2023-008-020', 
    'status': 'Not Started', 
    'category': 'Category', 
    'assignee': 'Jean Grey - Project 2', 
    'milestone': 'Milestone 19 - Project 2', 
    'issue_type': 'Type'
}, 
{
    'id': '20', 
    'pic': '/project2-picture20.jpg', 
    'man_in_charge': 'Victor Stone - Project 2', 
    'header': 'Task 20 Header - Project 2', 
    'content': 'Description of task 20 - Project 2 Task 20.', 
    'deadline': '2023-009-021', 
    'status': 'Completed', 
    'category': 'Other', 
    'assignee': 'Scott Summers - Project 2', 
    'milestone': 'Milestone 20 - Project 2', 
    'issue_type': 'Other'
}
];

export default ProjectData2;