const ProjectData1 = [
    {
      "id": "1",
      "pic": "/project1-picture1.jpg",
      "man_in_charge": "John Doe - Project 1",
      "header": "Banner Design Update - Project 1",
      "content": "Update the customer page layout for the website - Project 1 Task 1.",
      "deadline": "March 05, 2022",
      "status": "In Progress",
      "category": "Design",
      "assignee": "Alice Smith - Project 1",
      "milestone": "Website Redesign - Project 1",
      "issue_type": "Task"
    },
    {
      "id": "2",
      "pic": "/project1-picture2.jpg",
      "man_in_charge": "Jane Smith - Project 1",
      "header": "SEO Optimization - Project 1",
      "content": "Optimize the website's SEO for better search rankings - Project 1 Task 2.",
      "deadline": "April 10, 2022",
      "status": "Not Started",
      "category": "Marketing",
      "assignee": "Robert Johnson - Project 1",
      "milestone": "Digital Marketing Campaign - Project 1",
      "issue_type": "Task"
    },
    {
      "id": "3",
      "pic": "/project1-picture3.jpg",
      "man_in_charge": "Michael Brown - Project 1",
      "header": "Bug Fixing - Project 1",
      "content": "Fix critical bugs reported by users - Project 1 Task 3.",
      "deadline": "February 20, 2022",
      "status": "Completed",
      "category": "Development",
      "assignee": "David Wilson - Project 1",
      "milestone": "Bug Fixes - Project 1",
      "issue_type": "Bug"
    },
    {
      "id": "4",
      "pic": "/project1-picture4.jpg",
      "man_in_charge": "Emily Davis - Project 1",
      "header": "Content Writing - Project 1",
      "content": "Create engaging content for the blog posts - Project 1 Task 4.",
      "deadline": "March 15, 2022",
      "status": "In Progress",
      "category": "Content",
      "assignee": "Olivia Anderson - Project 1",
      "milestone": "Content Strategy - Project 1",
      "issue_type": "Task"
    },
    {
      "id": "5",
      "pic": "/project1-picture5.jpg",
      "man_in_charge": "William Lee - Project 1",
      "header": "Security Audit - Project 1",
      "content": "Conduct a security audit of the website - Project 1 Task 5.",
      "deadline": "April 30, 2022",
      "status": "Not Started",
      "category": "Security",
      "assignee": "Sophia White - Project 1",
      "milestone": "Security Enhancement - Project 1",
      "issue_type": "Task"
    },
    {
      "id": "6",
      "pic": "/project1-picture6.jpg",
      "man_in_charge": "Daniel Harris - Project 1",
      "header": "Mobile App Development - Project 1",
      "content": "Develop a mobile app for the company - Project 1 Task 6.",
      "deadline": "May 20, 2022",
      "status": "In Progress",
      "category": "Development",
      "assignee": "Ava Martinez - Project 1",
      "milestone": "Mobile App Launch - Project 1",
      "issue_type": "Feature"
    },
    {
      "id": "7",
      "pic": "/project1-picture7.jpg",
      "man_in_charge": "Sophia Johnson - Project 1",
      "header": "Customer Support Training - Project 1",
      "content": "Provide training to the customer support team - Project 1 Task 7.",
      "deadline": "March 31, 2022",
      "status": "Not Started",
      "category": "Training",
      "assignee": "Lucas Brown - Project 1",
      "milestone": "Training Program - Project 1",
      "issue_type": "Task"
    },
    {
      "id": "8",
      "pic": "/project1-picture8.jpg",
      "man_in_charge": "Ethan Martinez - Project 1",
      "header": "Graphic Design for Campaign - Project 1",
      "content": "Design graphics for the upcoming marketing campaign - Project 1 Task 8.",
      "deadline": "April 15, 2022",
      "status": "Not Started",
      "category": "Design",
      "assignee": "Chloe Adams - Project 1",
      "milestone": "Marketing Campaign - Project 1",
      "issue_type": "Task"
    },
    {
      "id": "9",
      "pic": "/project1-picture9.jpg",
      "man_in_charge": "Olivia Anderson - Project 1",
      "header": "Database Migration - Project 1",
      "content": "Migrate the database to a new server for improved performance - Project 1 Task 9.",
      "deadline": "March 25, 2022",
      "status": "In Progress",
      "category": "Database",
      "assignee": "Mia Davis - Project 1",
      "milestone": "Database Upgrade - Project 1",
      "issue_type": "Task"
    },
    {
      "id": "10",
      "pic": "/project1-picture10.jpg",
      "man_in_charge": "David Wilson - Project 1",
      "header": "User Interface Enhancement - Project 1",
      "content": "Enhance the user interface for better user experience - Project 1 Task 10.",
      "deadline": "May 10, 2022",
      "status": "Not Started",
      "category": "Development",
      "assignee": "Ella Smith - Project 1",
      "milestone": "UI/UX Improvements - Project 1",
      "issue_type": "Enhancement"
    },
    {
      "id": "11",
      "pic": "/project1-picture11.jpg",
      "man_in_charge": "John Newman - Project 1",
      "header": "New Project Management - Project 1",
      "content": "Manage a new project for the company - Project 1 Task 11.",
      "deadline": "June 30, 2023",
      "status": "In Progress",
      "category": "Project Management",
      "assignee": "Alice Johnson - Project 1",
      "milestone": "Project Kickoff - Project 1",
      "issue_type": "Project"
    },
    {
      "id": "12",
      "pic": "/project1-picture12.jpg",
      "man_in_charge": "Jane Richards - Project 1",
      "header": "Marketing Campaign - Project 1",
      "content": "Plan and execute a new marketing campaign - Project 1 Task 12.",
      "deadline": "July 15, 2023",
      "status": "Not Started",
      "category": "Marketing",
      "assignee": "Robert Davis - Project 1",
      "milestone": "Marketing Campaign Launch - Project 1",
      "issue_type": "Campaign"
    },
    {
      "id": "13",
      "pic": "/project1-picture13.jpg",
      "man_in_charge": "Michael Johnson - Project 1",
      "header": "App Development - Project 1",
      "content": "Develop a new mobile app for the company - Project 1 Task 13.",
      "deadline": "August 20, 2023",
      "status": "Not Started",
      "category": "Development",
      "assignee": "David Wilson - Project 1",
      "milestone": "App Development - Project 1",
      "issue_type": "Feature"
    },
    {
      "id": "14",
      "pic": "/project1-picture14.jpg",
      "man_in_charge": "Emily Anderson - Project 1",
      "header": "Content Strategy - Project 1",
      "content": "Develop a new content strategy for the blog - Project 1 Task 14.",
      "deadline": "September 10, 2023",
      "status": "In Progress",
      "category": "Content",
      "assignee": "Olivia Brown - Project 1",
      "milestone": "Content Strategy Update - Project 1",
      "issue_type": "Strategy"
    },
    {
      "id": "15",
      "pic": "/project1-picture15.jpg",
      "man_in_charge": "William Davis - Project 1",
      "header": "Security Audit - Project 1",
      "content": "Conduct a new security audit of the website - Project 1 Task 15.",
      "deadline": "October 25, 2023",
      "status": "Not Started",
      "category": "Security",
      "assignee": "Sophia Lee - Project 1",
      "milestone": "Security Enhancement - Project 1",
      "issue_type": "Security"
    },
    {
      "id": "16",
      "pic": "/project1-picture16.jpg",
      "man_in_charge": "Daniel Martin - Project 1",
      "header": "Customer Support Training - Project 1",
      "content": "Provide training to the customer support team - Project 1 Task 16.",
      "deadline": "November 10, 2023",
      "status": "Not Started",
      "category": "Training",
      "assignee": "Lucas White - Project 1",
      "milestone": "Training Program - Project 1",
      "issue_type": "Training"
    },
    {
      "id": "17",
      "pic": "/project1-picture17.jpg",
      "man_in_charge": "Sophia Jackson - Project 1",
      "header": "Graphic Design for Campaign - Project 1",
      "content": "Design graphics for the upcoming marketing campaign - Project 1 Task 17.",
      "deadline": "December 5, 2023",
      "status": "In Progress",
      "category": "Design",
      "assignee": "Ethan Martinez - Project 1",
      "milestone": "Campaign Design - Project 1",
      "issue_type": "Design"
    },
    {
      "id": "18",
      "pic": "/project1-picture18.jpg",
      "man_in_charge": "Ethan Wilson - Project 1",
      "header": "Database Migration - Project 1",
      "content": "Migrate the database to a new server for improved performance - Project 1 Task 18.",
      "deadline": "January 20, 2024",
      "status": "Completed",
      "category": "Database",
      "assignee": "Mia Smith - Project 1",
      "milestone": "Database Migration - Project 1",
      "issue_type": "Migration"
    },
    {
      "id": "19",
      "pic": "/project1-picture19.jpg",
      "man_in_charge": "Olivia Martin - Project 1",
      "header": "User Interface Enhancement - Project 1",
      "content": "Enhance the user interface for better user experience - Project 1 Task 19.",
      "deadline": "February 5, 2024",
      "status": "Close",
      "category": "Development",
      "assignee": "Ella Anderson - Project 1",
      "milestone": "UI/UX Enhancement - Project 1",
      "issue_type": "UI/UX"
    },
    {
      "id": "20",
      "pic": "/project1-picture20.jpg",
      "man_in_charge": "David White - Project 1",
      "header": "Quality Assurance Testing - Project 1",
      "content": "Perform quality assurance testing for a new software release - Project 1 Task 20.",
      "deadline": "March 15, 2024",
      "status": "Not Started",
      "category": "Quality Assurance",
      "assignee": "Chloe Davis - Project 1",
      "milestone": "Testing Phase - Project 1",
      "issue_type": "Testing"
    }
  ];
  
  export default ProjectData1;
  